import { Order } from "@/types/order";

export const dataOrder: Order[] = [
  {
    id: "ORD-1",
    userId: "USR-1",
    productId: "PRD-1",
    orderCode: "INV-0001",
    totalPrice: 150000,
    orderStatus: "PENDING",
    firstnameCustomer: "Ahmad",
    lastnameCustomer: "Fauzi",
    emailCustomer: "ahmad@example.com",
    phoneCustomer: "+62811111111",
    company: "TechCorp",
    address: "Jl. Merpati No. 1",
    country: "Indonesia",
    states: "Jawa Barat",
    zipCode: "40123",
    notes: "Tolong kirim cepat",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "ORD-2",
    userId: "USR-2",
    productId: "PRD-3",
    orderCode: "INV-0002",
    totalPrice: 320000,
    orderStatus: "PAID",
    firstnameCustomer: "Budi",
    lastnameCustomer: "Santoso",
    emailCustomer: "budi@example.com",
    phoneCustomer: "+62812222222",
    company: "IndoMart",
    address: "Jl. Kenari No. 4",
    country: "Indonesia",
    states: "Jawa Timur",
    zipCode: "60233",
    notes: "Packing rapi",
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    id: "ORD-3",
    userId: "USR-1",
    productId: "PRD-2",
    orderCode: "INV-0003",
    totalPrice: 275000,
    orderStatus: "SHIPPED",
    firstnameCustomer: "Citra",
    lastnameCustomer: "Lestari",
    emailCustomer: "citra@example.com",
    phoneCustomer: "+62813333333",
    company: "CreativeID",
    address: "Jl. Kelinci No. 8",
    country: "Indonesia",
    states: "DKI Jakarta",
    zipCode: "10310",
    notes: "",
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
  {
    id: "ORD-4",
    userId: "USR-3",
    productId: "PRD-5",
    orderCode: "INV-0004",
    totalPrice: 110000,
    orderStatus: "CANCELLED",
    firstnameCustomer: "Dewi",
    lastnameCustomer: "Amelia",
    emailCustomer: "dewi@example.com",
    phoneCustomer: "+62814444444",
    company: "FashionHub",
    address: "Jl. Anggrek No. 10",
    country: "Indonesia",
    states: "Banten",
    zipCode: "15023",
    notes: "Cancel request",
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    id: "ORD-5",
    userId: "USR-4",
    productId: "PRD-4",
    orderCode: "INV-0005",
    totalPrice: 450000,
    orderStatus: "DELIVERED",
    firstnameCustomer: "Eko",
    lastnameCustomer: "Prasetyo",
    emailCustomer: "eko@example.com",
    phoneCustomer: "+62815555555",
    company: "BuildIt",
    address: "Jl. Rajawali No. 21",
    country: "Indonesia",
    states: "DIY",
    zipCode: "55111",
    notes: "",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "ORD-6",
    userId: "USR-2",
    productId: "PRD-6",
    orderCode: "INV-0006",
    totalPrice: 99000,
    orderStatus: "PENDING",
    firstnameCustomer: "Fajar",
    lastnameCustomer: "Ramadhan",
    emailCustomer: "fajar@example.com",
    phoneCustomer: "+62816666666",
    company: "LightCode",
    address: "Jl. Sakura No. 2",
    country: "Indonesia",
    states: "Jawa Barat",
    zipCode: "40233",
    notes: "",
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    id: "ORD-7",
    userId: "USR-5",
    productId: "PRD-7",
    orderCode: "INV-0007",
    totalPrice: 750000,
    orderStatus: "PAID",
    firstnameCustomer: "Gilang",
    lastnameCustomer: "Pradana",
    emailCustomer: "gilang@example.com",
    phoneCustomer: "+62817777777",
    company: "DevStudio",
    address: "Jl. Pahlawan No. 3",
    country: "Indonesia",
    states: "Jawa Tengah",
    zipCode: "50122",
    notes: "",
    createdAt: new Date("2025-01-07"),
    updatedAt: new Date("2025-01-07"),
  },
  {
    id: "ORD-8",
    userId: "USR-6",
    productId: "PRD-3",
    orderCode: "INV-0008",
    totalPrice: 210000,
    orderStatus: "SHIPPED",
    firstnameCustomer: "Hana",
    lastnameCustomer: "Putri",
    emailCustomer: "hana@example.com",
    phoneCustomer: "+62818888888",
    company: "MediaPro",
    address: "Jl. Melati No. 12",
    country: "Indonesia",
    states: "Bali",
    zipCode: "80115",
    notes: "",
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    id: "ORD-9",
    userId: "USR-7",
    productId: "PRD-9",
    orderCode: "INV-0009",
    totalPrice: 560000,
    orderStatus: "DELIVERED",
    firstnameCustomer: "Indra",
    lastnameCustomer: "Saputra",
    emailCustomer: "indra@example.com",
    phoneCustomer: "+62819999999",
    company: "ShopMore",
    address: "Jl. Nangka No. 6",
    country: "Indonesia",
    states: "Sumatera Utara",
    zipCode: "20219",
    notes: "",
    createdAt: new Date("2025-01-09"),
    updatedAt: new Date("2025-01-09"),
  },
  {
    id: "ORD-10",
    userId: "USR-8",
    productId: "PRD-10",
    orderCode: "INV-0010",
    totalPrice: 180000,
    orderStatus: "PAID",
    firstnameCustomer: "Joko",
    lastnameCustomer: "Widodo",
    emailCustomer: "joko@example.com",
    phoneCustomer: "+62810000000",
    company: "LocalStore",
    address: "Jl. Kenanga No. 7",
    country: "Indonesia",
    states: "Kalimantan Timur",
    zipCode: "75243",
    notes: "",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
  // Tambah hingga 20 (pola sama)
  ...Array.from({ length: 10 }, (_, i) => {
    const n = i + 11;
    return {
      id: `ORD-${n}`,
      userId: `USR-${(n % 8) + 1}`,
      productId: `PRD-${(n % 10) + 1}`,
      orderCode: `INV-00${n}`,
      totalPrice: n * 50000,
      orderStatus: ["PENDING", "PAID", "SHIPPED", "DELIVERED", "CANCELLED"][
        n % 5
      ],
      firstnameCustomer: `Customer${n}`,
      lastnameCustomer: `Test${n}`,
      emailCustomer: `customer${n}@example.com`,
      phoneCustomer: `+6281${n}000000`,
      company: `Company ${n}`,
      address: `Jl. Dummy No. ${n}`,
      country: "Indonesia",
      states: "Random State",
      zipCode: `40${n}23`,
      notes: "",
      createdAt: new Date(`2025-01-${n}`),
      updatedAt: new Date(`2025-01-${n}`),
    };
  }),
];
